### ISSUE TITLE
Should document the effects of using this with perl -c

### ISSUE THREAD

**Issue by robrwo** [rafl/namespace-autoclean#5]
If you have a module with something like

```
use Foo qw/ bar /; # imports the "bar" function
use namespace::autoclean;

...

bar 'something';
```

Then running `perl -c MyModule.pm` returns syntax errors for the "foo" function.

For example, using Moose, the "has" function causes syntax errors.

**Comment by karenetheridge** [comment]
It shouldn't.  Please send a repro case to rt.cpan.org?

**Comment by robrwo** [comment]
I'm having trouble reproducing this. Might have been a typo somewhere.
